/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.VolunteerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HealthEnterprise;
import Business.HomelessPerson;
import Business.Network.Network;
import Business.Organization.HospitalOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalAllocationWorkRequest;
import Email.SendGridEmail;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Keerthana
 */
public class RegisterHomelessJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterHomelessJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem business;
//    JScrollPane scrollPane = new JScrollPane(RegisterHomelessJPanel);
//    scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
//    scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
//    scrollPane.setBounds(50, 30, 300, 50);

    public RegisterHomelessJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.business = business;
    }

    private boolean emailPatternCorrect() {
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(txtFieldEmailAddress.getText());
        boolean b = m.matches();
        return b;
    }

    public boolean Datevalidate() {
        Pattern pattern;
        Matcher matcher;

        pattern = Pattern.compile("(0?[1-9]|[12][0-9]|3[01])/(0?[1-9]|1[012])/((19|20)\\d\\d)");

        matcher = pattern.matcher(txtFieldDOB.getText());

        if (matcher.matches()) {

            matcher.reset();

            if (matcher.find()) {

                String day = matcher.group(1);
                String month = matcher.group(2);
                int year = Integer.parseInt(matcher.group(3));

                if (day.equals("31")
                        && (month.equals("4") || month.equals("6") || month.equals("9")
                        || month.equals("11") || month.equals("04") || month.equals("06")
                        || month.equals("09"))) {
                    return false; // only 1,3,5,7,8,10,12 has 31 days
                } else if (month.equals("2") || month.equals("02")) {
                    //leap year
                    if (year % 4 == 0) {
                        if (day.equals("30") || day.equals("31")) {
                            return false;
                        } else {
                            return true;
                        }
                    } else {
                        if (day.equals("29") || day.equals("30") || day.equals("31")) {
                            return false;
                        } else {
                            return true;
                        }
                    }
                } else {
                    return true;
                }
            } else {
                return false;
            }
        } else {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFieldQualifications = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtFieldAccomplishments = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtFieldName = new javax.swing.JTextField();
        txtFieldDOB = new javax.swing.JTextField();
        txtFieldDependents = new javax.swing.JTextField();
        txtFieldCity = new javax.swing.JTextField();
        txtFieldAddress = new javax.swing.JTextField();
        txtFieldSSNNo = new javax.swing.JTextField();
        txtFieldContactNo = new javax.swing.JTextField();
        txtFieldEmailAddress = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        radioBtnFemaleGender = new javax.swing.JRadioButton();
        radioBtnMaleGender = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtFieldEmploymentStatus = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtFieldTotalIncome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        radioBtnCriminalCheckYes = new javax.swing.JRadioButton();
        radioBtnCriminalCheckNo = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        radioBtnillnessYes = new javax.swing.JRadioButton();
        radioBtnillnessNo = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        radioBtnCarrierYes = new javax.swing.JRadioButton();
        radioBtnCarrierNo = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        radioBtnDiseaseYes = new javax.swing.JRadioButton();
        radioBtnDiseaseNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        textFieldPrefLocation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(223, 190, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(215, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(196, 196, 196))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addGap(67, 67, 67))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 963, -1, 0));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel5.setText("Any accomplishments :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 171, 28));
        add(txtFieldQualifications, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 259, 29));

        jLabel11.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel11.setText("Date of Birth:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 125, 120, 30));
        add(txtFieldAccomplishments, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, 259, 29));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText(" Education Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 590, 30));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel3.setText("Qualifications:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 171, 29));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel6.setText("Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 85, 120, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel12.setText("Gender:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 174, 120, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel13.setText("Dependents:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 30));

        jLabel15.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel15.setText("Current Location:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 210, 150, 30));

        jLabel31.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel31.setText("Current City:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 120, 30));
        add(txtFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 86, 259, 29));
        add(txtFieldDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 259, 29));

        txtFieldDependents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldDependentsActionPerformed(evt);
            }
        });
        add(txtFieldDependents, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 259, 29));
        add(txtFieldCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 259, 29));

        txtFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldAddressActionPerformed(evt);
            }
        });
        add(txtFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 259, 29));
        add(txtFieldSSNNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 259, 29));
        add(txtFieldContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 259, 29));
        add(txtFieldEmailAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 259, 29));

        jLabel14.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel14.setText("SSN");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 120, 30));

        jLabel32.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel32.setText("Email Address:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 99, 30));

        jLabel34.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel34.setText("Contact Number:");
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, 30));

        radioBtnFemaleGender.setText("Female");
        radioBtnFemaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnFemaleGenderActionPerformed(evt);
            }
        });
        add(radioBtnFemaleGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 179, -1, -1));

        radioBtnMaleGender.setText("Male");
        radioBtnMaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnMaleGenderActionPerformed(evt);
            }
        });
        add(radioBtnMaleGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 179, -1, -1));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel25.setText(" Financial Details");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 510, 30));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel7.setText("Employment Status:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 260, 34));
        add(txtFieldEmploymentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 270, 29));

        jLabel29.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel29.setText("Monthly income from all the sources:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 230, 29));
        add(txtFieldTotalIncome, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 380, 240, 29));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText(" Information for Criminal Check ");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 430, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel18.setText("Have you ever pled guilty to OR being convicted OR found guilty of misdemeanor in any U.S. or non-U.S. OR military court?");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 430, 30));

        radioBtnCriminalCheckYes.setText("Yes");
        radioBtnCriminalCheckYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCriminalCheckYesActionPerformed(evt);
            }
        });
        add(radioBtnCriminalCheckYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        radioBtnCriminalCheckNo.setText("No");
        radioBtnCriminalCheckNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCriminalCheckNoActionPerformed(evt);
            }
        });
        add(radioBtnCriminalCheckNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel16.setText(" Medical Details");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 570, 30));

        btnSubmit.setBackground(new java.awt.Color(114, 158, 161));
        btnSubmit.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 700, 250, 50));

        btnBack.setBackground(new java.awt.Color(114, 158, 161));
        btnBack.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBack.setText("< ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 40));

        jLabel27.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel27.setText("Have you had any major illness? ");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 566, 20));

        radioBtnillnessYes.setText("Yes");
        radioBtnillnessYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnillnessYesActionPerformed(evt);
            }
        });
        add(radioBtnillnessYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 550, -1, -1));

        radioBtnillnessNo.setText("No");
        radioBtnillnessNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnillnessNoActionPerformed(evt);
            }
        });
        add(radioBtnillnessNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 550, -1, -1));

        jLabel26.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel26.setText("Have you ever been told that you are a carrier of a genetic/inherited disease? ");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 567, 20));

        radioBtnCarrierYes.setText("Yes");
        radioBtnCarrierYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCarrierYesActionPerformed(evt);
            }
        });
        add(radioBtnCarrierYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, -1, -1));

        radioBtnCarrierNo.setText("No");
        radioBtnCarrierNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnCarrierNoActionPerformed(evt);
            }
        });
        add(radioBtnCarrierNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 590, -1, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel28.setText("Have you ever been told that you have a genetic/inherited disease? ");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 567, 20));

        radioBtnDiseaseYes.setText("Yes");
        radioBtnDiseaseYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDiseaseYesActionPerformed(evt);
            }
        });
        add(radioBtnDiseaseYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 630, -1, -1));

        radioBtnDiseaseNo.setText("No");
        radioBtnDiseaseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnDiseaseNoActionPerformed(evt);
            }
        });
        add(radioBtnDiseaseNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 630, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel4.setText("Preferred Location:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 120, 30));
        add(textFieldPrefLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 259, 29));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(104, 144, 146));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("REGISTER HOMELESS PERSON");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 6, 950, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel1.setText("US $");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 40, 20));

        jLabel17.setToolTipText("");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 220, 210));
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnCriminalCheckYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCriminalCheckYesActionPerformed
        // TODO add your handling code here:
        radioBtnCriminalCheckNo.setSelected(false);
    }//GEN-LAST:event_radioBtnCriminalCheckYesActionPerformed

    private void radioBtnillnessYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnillnessYesActionPerformed
        // TODO add your handling code here:
        radioBtnillnessNo.setSelected(false);
    }//GEN-LAST:event_radioBtnillnessYesActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        VolunteerWorkAreaJPanel dwjp = (VolunteerWorkAreaJPanel) component;
        dwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (txtFieldName.getText().equals("") || txtFieldDOB.getText().equals("")
                || txtFieldCity.getText().equals("")
                || txtFieldAddress.getText().equals("")
                || txtFieldSSNNo.getText().equals("")
                || txtFieldEmailAddress.getText().equals("")
                || txtFieldDependents.getText().equals("")
                || txtFieldQualifications.getText().equals("")
                || txtFieldAccomplishments.getText().equals("")
                || txtFieldEmploymentStatus.getText().equals("")
                || txtFieldTotalIncome.getText().equals("")
                || textFieldPrefLocation.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please Enter all the Required Fields!");
            return;
        }

        if (!Datevalidate()) {
            JOptionPane.showMessageDialog(null, "Date of Birth should be in the format: DD/MM/YYYY");
            return;
        }

        if (!emailPatternCorrect()) {
            JOptionPane.showMessageDialog(null, "Email should be in the format: <name>@<company>.<domain>");
            return;
        }

        try {
            Long.parseLong(txtFieldContactNo.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for Contact No");
            return;
        }

        if (txtFieldContactNo.getText().length() != 10) {
            JOptionPane.showMessageDialog(null, "Contact No should be exactly 10 digits");
            return;
        }

        if (txtFieldSSNNo.getText().length() != 9) {
            JOptionPane.showMessageDialog(null, "Enter only 9 digits of SSN (without '-')");
            return;
        }

        try {
            Integer.parseInt(txtFieldDependents.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for Dependents");
            return;
        }
        try {
            Integer.parseInt(txtFieldTotalIncome.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please type in a number for Income");
            return;
        }

        if (Integer.parseInt(txtFieldTotalIncome.getText()) > 1500) {
            JOptionPane.showMessageDialog(null, "The person cannot be allowed to register as his monthly income is greater than $1500.");
            return;
        }
        if (!radioBtnMaleGender.isSelected() && !radioBtnFemaleGender.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select the Gender!");
            return;
        }
        if (!radioBtnCriminalCheckYes.isSelected() && !radioBtnCriminalCheckNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for criminal record!");
            return;
        }
        if (!radioBtnillnessYes.isSelected() && !radioBtnillnessNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for illness criteria!");
            return;
        }
        if (!radioBtnCarrierYes.isSelected() && !radioBtnCarrierNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for carrier of disease!");
            return;
        }
        if (!radioBtnDiseaseYes.isSelected() && !radioBtnDiseaseNo.isSelected()) {
            JOptionPane.showMessageDialog(null, "Select a yes or no for genetic inherited disease");
            return;
        }

        String name = txtFieldName.getText();
        String dob = txtFieldDOB.getText();
        String city = txtFieldCity.getText();
        String addresss = txtFieldAddress.getText();
        String ssnNo = txtFieldSSNNo.getText();
        String contactNo = txtFieldContactNo.getText();
        String emailAddresss = txtFieldEmailAddress.getText();
        int dependents = Integer.parseInt(txtFieldDependents.getText());
        String qualifications = txtFieldQualifications.getText();
        String accomplishments = txtFieldAccomplishments.getText();
        String employmentStatus = txtFieldEmploymentStatus.getText();
        int income = Integer.parseInt(txtFieldTotalIncome.getText());
        String prefLocation = textFieldPrefLocation.getText();
        String gender = "Male";
        if (radioBtnFemaleGender.isSelected()) {
            gender = "Female";
        }
        boolean criminalRecord = false;
        if (radioBtnCriminalCheckYes.isSelected()) {
            criminalRecord = true;
        }
        boolean majorIllnes = false;
        if (radioBtnillnessYes.isSelected()) {
            majorIllnes = true;
        }
        boolean carrierDisease = false;
        if (radioBtnCarrierYes.isSelected()) {
            carrierDisease = true;
        }
        boolean geneticDisease = false;
        if (radioBtnDiseaseYes.isSelected()) {
            geneticDisease = true;
        }

        try {
            SendGridEmail.sendMail(emailAddresss);
        } catch (IOException ex) {
            Logger.getLogger(RegisterHomelessJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        HomelessPerson person = new HomelessPerson(name, dob, city, addresss, ssnNo,
                contactNo, emailAddresss, dependents, qualifications, accomplishments,
                employmentStatus, income, gender, criminalRecord, majorIllnes, carrierDisease, geneticDisease, prefLocation);
//        ShelterAllocateWorkRequest request = new ShelterAllocateWorkRequest();
//        request.setHomelessPerson(person);
//        request.setMessage("Shelter search");
//        request.setSender(userAccount);
//        request.setStatus("Sent");
//        Date d = new Date();
//        request.setRequestDate(d);
//        Organization org = null;
//
//        for (Network network : business.getNetworkList()) {
//            //Step 2.a: check against each enterprise
//            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//                if (enterprise instanceof PublicShelterEnterprise) {
//                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//                        if (organization instanceof ShelterAllocationOrganization) {
//                            org = organization;
//                            break;
//                        }
//                    }
//                }
//            }
//        }
//        if (org != null) {
//            org.getWorkQueue().getWorkRequestList().add(request);
//            userAccount.getWorkQueue().getWorkRequestList().add(request);
//        }
//        JOptionPane.showMessageDialog(this, "Request Sent to Shelter Allocator!");

//        MealDistributionWorkRequest mealDistributionWorkRequest = new MealDistributionWorkRequest();
//        mealDistributionWorkRequest.setHomelessPerson(person);
//        mealDistributionWorkRequest.setMessage("Meal Plan Allocation Request");
//        mealDistributionWorkRequest.setSender(userAccount);
//        mealDistributionWorkRequest.setStatus("Sent");
//        Date date = new Date();
//        mealDistributionWorkRequest.setRequestDate(date);
//        Organization mealdistributionorganization = null;
//
//        for (Network network : business.getNetworkList()) {
//            //Step 2.a: check against each enterprise
//            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
//                if (enterprise instanceof MealPlanEnterprise) {
//                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
//                        if (organization instanceof MealDistributionOrganization) {
//                            mealdistributionorganization = organization;
//                            break;
//                        }
//                    }
//                }
//            }
//        }
//        if (mealdistributionorganization != null) {
//            mealdistributionorganization.getWorkQueue().getWorkRequestList().add(mealDistributionWorkRequest);
//            userAccount.getWorkQueue().getWorkRequestList().add(mealDistributionWorkRequest);
//        }
//        JOptionPane.showMessageDialog(this, "Request Sent to Meal Distribution Organization!");
        HospitalAllocationWorkRequest allocationWorkRequest = new HospitalAllocationWorkRequest();
        allocationWorkRequest.setHomelessPerson(person);
        allocationWorkRequest.setMessage("Hospital Allocation Request");
        allocationWorkRequest.setSender(userAccount);
        allocationWorkRequest.setStatus("Sent");
        Date date = new Date();
        allocationWorkRequest.setRequestDate(date);
        Organization hospitalAllocationOganization = null;

        for (Network network : business.getNetworkList()) {
            //Step 2.a: check against each enterprise
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof HealthEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof HospitalOrganization) {
                            hospitalAllocationOganization = organization;
                            break;
                        }
                    }
                }
            }
        }
        if (hospitalAllocationOganization != null) {
            hospitalAllocationOganization.getWorkQueue().getWorkRequestList().add(allocationWorkRequest);
            userAccount.getWorkQueue().getWorkRequestList().add(allocationWorkRequest);
        }
        JOptionPane.showMessageDialog(this, "Request Sent to Hospital Allocation!");

        clearFields();
    }//GEN-LAST:event_btnSubmitActionPerformed

    public void clearFields() {
        txtFieldName.setText("");
        txtFieldDOB.setText("");
        txtFieldCity.setText("");
        txtFieldAddress.setText("");
        txtFieldSSNNo.setText("");
        txtFieldContactNo.setText("");
        txtFieldEmailAddress.setText("");
        txtFieldDependents.setText("");
        txtFieldQualifications.setText("");
        txtFieldAccomplishments.setText("");
        txtFieldEmploymentStatus.setText("");
        txtFieldTotalIncome.setText("");
        textFieldPrefLocation.setText("");
        radioBtnMaleGender.setSelected(false);
        radioBtnFemaleGender.setSelected(false);
        radioBtnCriminalCheckYes.setSelected(false);
        radioBtnCriminalCheckNo.setSelected(false);
        radioBtnillnessYes.setSelected(false);
        radioBtnillnessNo.setSelected(false);
        radioBtnCarrierYes.setSelected(false);
        radioBtnCarrierNo.setSelected(false);
        radioBtnDiseaseYes.setSelected(false);
        radioBtnDiseaseNo.setSelected(false);

    }
    private void radioBtnMaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnMaleGenderActionPerformed
        radioBtnFemaleGender.setSelected(false);
    }//GEN-LAST:event_radioBtnMaleGenderActionPerformed

    private void radioBtnFemaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnFemaleGenderActionPerformed
        // TODO add your handling code here:
        radioBtnMaleGender.setSelected(false);
    }//GEN-LAST:event_radioBtnFemaleGenderActionPerformed

    private void radioBtnCriminalCheckNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCriminalCheckNoActionPerformed
        // TODO add your handling code here:
        radioBtnCriminalCheckYes.setSelected(false);
    }//GEN-LAST:event_radioBtnCriminalCheckNoActionPerformed

    private void radioBtnillnessNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnillnessNoActionPerformed
        // TODO add your handling code here:
        radioBtnillnessYes.setSelected(false);
    }//GEN-LAST:event_radioBtnillnessNoActionPerformed

    private void radioBtnCarrierYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCarrierYesActionPerformed
        // TODO add your handling code here:
        radioBtnCarrierNo.setSelected(false);
    }//GEN-LAST:event_radioBtnCarrierYesActionPerformed

    private void radioBtnCarrierNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnCarrierNoActionPerformed
        // TODO add your handling code here:
        radioBtnCarrierYes.setSelected(false);
    }//GEN-LAST:event_radioBtnCarrierNoActionPerformed

    private void radioBtnDiseaseYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDiseaseYesActionPerformed
        // TODO add your handling code here:
        radioBtnDiseaseNo.setSelected(false);
    }//GEN-LAST:event_radioBtnDiseaseYesActionPerformed

    private void radioBtnDiseaseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtnDiseaseNoActionPerformed
        // TODO add your handling code here:
        radioBtnDiseaseYes.setSelected(false);
    }//GEN-LAST:event_radioBtnDiseaseNoActionPerformed

    private void txtFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldAddressActionPerformed

    private void txtFieldDependentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldDependentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldDependentsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton radioBtnCarrierNo;
    private javax.swing.JRadioButton radioBtnCarrierYes;
    private javax.swing.JRadioButton radioBtnCriminalCheckNo;
    private javax.swing.JRadioButton radioBtnCriminalCheckYes;
    private javax.swing.JRadioButton radioBtnDiseaseNo;
    private javax.swing.JRadioButton radioBtnDiseaseYes;
    private javax.swing.JRadioButton radioBtnFemaleGender;
    private javax.swing.JRadioButton radioBtnMaleGender;
    private javax.swing.JRadioButton radioBtnillnessNo;
    private javax.swing.JRadioButton radioBtnillnessYes;
    private javax.swing.JTextField textFieldPrefLocation;
    private javax.swing.JTextField txtFieldAccomplishments;
    private javax.swing.JTextField txtFieldAddress;
    private javax.swing.JTextField txtFieldCity;
    private javax.swing.JTextField txtFieldContactNo;
    private javax.swing.JTextField txtFieldDOB;
    private javax.swing.JTextField txtFieldDependents;
    private javax.swing.JTextField txtFieldEmailAddress;
    private javax.swing.JTextField txtFieldEmploymentStatus;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldQualifications;
    private javax.swing.JTextField txtFieldSSNNo;
    private javax.swing.JTextField txtFieldTotalIncome;
    // End of variables declaration//GEN-END:variables
}
